Repository tienld-0801/tilokit, pull requests merged in 2025-08, with the labels that each got.

#20 ✨ feat: enhance release workflow with multi-platform optimizations
  .github/workflows/pr-auto-label.yml
  .github/workflows/release.yml
  .github/workflows/setup-labels.yml
  CHANGELOG.md
  scripts/install.sh
Labels: ✨ Enhancement

#21 🐛 fix: resolve regex syntax errors in generate-changelog.sh
  scripts/generate-changelog.sh
Labels: 🐛 Bug

#25 ♻️ refactor: reset to v0.1.0-dev with comprehensive changelog
  .github/workflows/release.yml
  CHANGELOG.md
  Makefile
  cmd/root.go
  cmd/update.go
  cmd/version.go
  scripts/generate-changelog.sh
Labels: ♻️ Refactor

#27 🐛 fix: prepare comprehensive v0.1.0 dev release
  .github/workflows/release.yml
  .github/workflows/validate-commits.yml
  .husky/README.md
  .husky/check-hooks.sh
  .husky/ci-check-commits.sh
  .husky/hooks/commit-msg
  .husky/hooks/install-hooks.sh
  .husky/hooks/pre-commit
  CHANGELOG.md
  Makefile
Labels: 🐛 Bug

#28 ♻️ refactor: complete CLI structure refactoring and config system cleanup
  .github/workflows/ci.yml
  README.md
  cmd/list.go
  cmd/root.go
  cmd/version.go
  internal/cli/constants.go
  internal/cli/handlers.go
  internal/cli/manager.go
  internal/cli/project.go
  internal/cli/update.go
  internal/cli/validation.go
  internal/config/config.go
  internal/utils/helpers.go
  main.go
  scripts/install.sh
  scripts/status.sh
  tilokit.example.yaml
Labels: ♻️ Refactor

#30 🐛 fix: correct version file path in release script
  scripts/release.sh
  scripts/test-release.sh
Labels: 🐛 Bug

#37 🐛 fix: single commit release flow
  scripts/release.sh
  scripts/test-release.sh
Labels: 🐛 Bug

#40 🐛 fix: resolve lint errors and enhance PR auto-labeling system
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/markdown.yml
  .github/workflows/pr-auto-label.yml
  .github/workflows/release.yml
  .github/workflows/setup-labels.yml
  .github/workflows/validate-commits.yml
  .golangci.yml
  cmd/root.go
  internal/cli/handlers.go
  internal/cli/manager.go
  internal/cli/project.go
  internal/cli/update.go
  internal/cli/validation.go
  internal/core/engine/engine.go
  internal/plugins/builders/rollup.go
  internal/plugins/builders/vite.go
  internal/plugins/builders/webpack.go
  internal/plugins/frameworks/csharp.go
  internal/plugins/frameworks/desktop.go
  internal/plugins/frameworks/golang.go
  internal/plugins/frameworks/java.go
  internal/plugins/frameworks/mobile.go
  internal/plugins/frameworks/nodejs.go
  internal/plugins/frameworks/php.go
  internal/plugins/frameworks/python.go
  internal/plugins/frameworks/ruby.go
  internal/plugins/frameworks/rust.go
  internal/plugins/frameworks/vue.go
  internal/plugins/templates/template.go
  pkg/constants/constants.go
Labels: 🐛 Bug, ❓ Needs Review

#41 ♻️ refactor: simplify release system to use GitHub native release notes
  .github/release.yml
  .github/workflows/pr-auto-label.yml
  .github/workflows/release.yml
  .husky/ci-check-commits.sh
  .husky/hooks/pre-commit
  .versionrc
  CHANGELOG.md
  Makefile
  scripts/generate-changelog.sh
  scripts/release.sh
Labels: ♻️ Refactor, ❓ Needs Review

#42 🐛 fix: update constants path in release script
  scripts/release.sh
Labels: 🐛 Bug, ❓ Needs Review

#43 📚 docs: update README with current Go version and comprehensive SEO i…
  README.md
Labels: 📚 Documentation, ❓ Needs Review

#46 ✨ feat: add GitHub Community Standards compliance
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/maintenance-task.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/SECURITY.md
  .github/config.yml
Labels: ✨ Enhancement, ❓ Needs Review

#47 🐛 fix: remove 'Release' prefix from tag title
  .github/scripts/release.sh
Labels: 🐛 Bug, ❓ Needs Review

#48 🐛 fix: update Makefile to use correct release script path
  Makefile
Labels: 🐛 Bug

#49 🐛 fix: update sed syntax for macOS compatibility
  .github/scripts/release.sh
Labels: 🐛 Bug, ❓ Needs Review

#51 ✨ feat: add revert-release make target and revert version
  Makefile
  pkg/constants/constants.go
Labels: ✨ Enhancement, ❓ Needs Review

#52 ✨ feat: add comprehensive framework templates for all languages
  .github/workflows/ci.yml
  internal/cli/manager.go
  internal/cli/project.go
  internal/plugins/frameworks/react.go
  internal/templates/angular/angular.go
  internal/templates/csharp/aspnet.go
  internal/templates/go/echo.go
  internal/templates/go/fiber.go
  internal/templates/go/gin.go
  internal/templates/go/gin/go.mod.tmpl
  internal/templates/go/gin/main.go.tmpl
  internal/templates/java/spring.go
  internal/templates/kotlin/spring.go
  internal/templates/nextjs/nextjs-tailwind.go
  internal/templates/nextjs/nextjs.go
  internal/templates/nodejs/express.go
  internal/templates/php/laravel.go
  internal/templates/python/django.go
  internal/templates/python/fastapi.go
  internal/templates/python/flask.go
  internal/templates/react/vite-js.go
  internal/templates/react/vite-ts.go
  internal/templates/ruby/rails.go
  internal/templates/svelte/vite-js.go
  internal/templates/vue/vite-js.go
  internal/templates/vue/vite-ts.go
  pkg/constants/constants.go
  templates/python/django/Dockerfile.tmpl
  templates/python/django/requirements.txt.tmpl
  templates/rust/actix/Cargo.toml.tmpl
  templates/rust/actix/src/main.rs.tmpl
Labels: ✨ Enhancement, ❓ Needs Review

#58 🧹 chore: upgrade go version 1.25.0
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .golangci.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  go.mod
  internal/templates/go/echo.go
  internal/templates/go/fiber.go
  internal/templates/go/gin.go
  internal/templates/go/gin/go.mod.tmpl
  pkg/constants/constants.go
Labels: 🧹 Maintenance, ❓ Needs Review

#62 ✨ feat: enhance avatar styling and add Google site verification
  .github/google24e6d5117676f6d4.html
  .github/release-page.html
  .github/scripts/update-readme.sh
Labels: ✨ Enhancement, ❓ Needs Review

#63 🐛 fix: and enhance file bug url
  .github/release-page.html
  .github/security.txt
  README.md
  assets/banner.png
  assets/logo.svg
Labels: 🐛 Bug, ❓ Needs Review

#64 🐛 fix: GitHub pages and version update
  .github/scripts/update-readme.sh
  .github/workflows/release.yml
  README.md
Labels: 🐛 Bug, ❓ Needs Review

#67 🐛 fix: timeout ci
  .github/workflows/release.yml
Labels: 🐛 Bug, ❓ Needs Review

#69 🐛 fix: Setup funding yml
  .github/CONTRIBUTING.md
  .github/FUNDING.yml
  .github/README.md
  .github/scripts/release.sh
  .github/scripts/update-readme.sh
Labels: 🐛 Bug, ❓ Needs Review

#71 📚 docs: update LICENSE and README.md license section
  .github/README.md
  LICENSE
Labels: 📚 Documentation, ❓ Needs Review

#72 ♻️ refactor: remove package manager options
  .env.example
  .gitflow
  .github/README.md
  .github/workflows/ci.yml
  .husky/hooks/pre-commit
  .markdownlint.yml
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  Makefile
  go.mod
  go.sum
  internal/cli/manager.go
  internal/cli/project.go
  internal/config/config.go
  internal/core/context/context.go
  internal/plugins/frameworks/nextjs.go
  internal/plugins/frameworks/nuxtjs.go
  internal/plugins/frameworks/react.go
  internal/plugins/frameworks/vue.go
  internal/templates/react/vite-js.go
  internal/templates/react/vite-ts.go
  internal/templates/vue/vite-js.go
  internal/templates/vue/vite-ts.go
  internal/utils/env.go
Labels: ♻️ Refactor, ❓ Needs Review

#73 ✨ feat: refactor vue template
  .vscode/settings.json
  internal/core/context/context.go
  internal/plugins/frameworks/react.go
  internal/plugins/frameworks/vue.go
  internal/plugins/templates/template.go
  internal/templates/react/vite-js.go
  internal/templates/react/vite-ts.go
  internal/templates/vue/vite-common.go
  internal/templates/vue/vite-js.go
  internal/templates/vue/vite-ts.go
  pkg/constants/constants.go
Labels: ✨ Enhancement, ❓ Needs Review

#75 ✨ feat: add Node.js backend framework support (Express, Fastify, NestJS)
  internal/cli/project.go
  internal/core/registry/registry.go
  internal/plugins/frameworks/express.go
  internal/plugins/frameworks/fastify.go
  internal/plugins/frameworks/nest.go
  internal/plugins/frameworks/nodejs.go
  internal/plugins/frameworks/react.go
  internal/templates/node/express.go
  internal/templates/node/fastify.go
  internal/templates/node/nestjs.go
  internal/templates/nodejs/express.go
  pkg/constants/constants.go
  pkg/constants/files.go
Labels: ✨ Enhancement, ❓ Needs Review

#76 ♻️ refactor: correct template variable format to use dot notation
  internal/plugins/frameworks/nextjs.go
  internal/plugins/frameworks/nuxtjs.go
  internal/plugins/templates/template.go
  internal/templates/nextjs/app.go
  internal/templates/nextjs/pages.go
  internal/templates/nuxtjs/nuxtjs.go
Labels: ♻️ Refactor, ❓ Needs Review

#81 ✨ feat: integrate Bubble Tea animated progress bar
  go.mod
  go.sum
  internal/cli/project.go
  internal/ui/progress.go
Labels: ✨ Enhancement, ❓ Needs Review

#84 ♻️ refactor: separate Python frameworks into individual plugins
  internal/cli/generation/orchestrator.go
  internal/cli/generation/registry/registry.go
  internal/plugins/frameworks/django.go
  internal/plugins/frameworks/fastapi.go
  internal/plugins/frameworks/flask.go
  internal/plugins/frameworks/python.go
  internal/templates/python/django.go
  internal/templates/python/fastapi.go
  internal/templates/python/flask.go
  pkg/constants/constants.go
Labels: ♻️ Refactor, ❓ Needs Review

#86 🧪 test: testing webhook
  .github/workflows/notifications.yml
Labels: 🧪 Test, ❓ Needs Review

#87 ✨ feat: add Discord community integration
  .github/CONTRIBUTING.md
  .github/README.md
  .github/release-page.html
  internal/cli/handlers.go
  internal/utils/helpers.go
Labels: ✨ Enhancement, ❓ Needs Review
